### ISSUE TITLE
Don't compile scss files that start with an underscore.

### ISSUE THREAD

**Issue by dotDeeka** [antonj/scss-mode#26]
It is an sass convention to not compile files that start with an underscore. Those files are partials and are included into another file that doesn't start with an underscore.

I believe when using sass watch, saving a .scss file that starts with an underscore the file it is included in is compiled.

**Comment by antonj** [comment]
I would suggest not using the 'compile when save' at all if you are working with more complex scss combinations. Use sass watch or a task runner like gulp or grunt to compile your sass.

**Comment by dotDeeka** [comment]
I was just thinking having the 'compile when save' on by default isn't the best idea since most people I know who use sass or scss use a task runner like gulp or grunt to compile it on change.

**Comment by antonj** [comment]
Ah, true, forgot it was on by default, fixed in b010d134f499c4b4ad33fe8a669a81e9a531b0b2
