### ISSUE TITLE
mode hook?

### ISSUE THREAD

**Issue by carljm** [antonj/scss-mode#29]
I'd like to automatically turn flymake mode on anytime I enter scss-mode, but I can't see how to do this. Parallel to other modes, I'd expect an `scss-mode-hook` or similar where I could set `flymake-mode t`, but I don't see that hook.

**Comment by antonj** [comment]
It's there, try something like this, it works

```elisp
(defun aj-scss-mode-hook()
  (setq cssm-indent-function #'cssm-c-style-indenter)
  ;; (setq scss-sass-options '("--style" "compressed"))
  (rainbow-mode t))
(add-hook 'scss-mode-hook 'aj-scss-mode-hook)
```

**Comment by carljm** [comment]
Thanks! I guess I didn't see it as a Customize option and didn't see it by grepping `scss-mode.el`, so I assumed it wasn't there. Clearly it works in some magical way that I don't understand at all :-)
